[theme]
primaryColor = "#38bdf8"
backgroundColor = "#05070a"
secondaryBackgroundColor = "#0d1321"
textColor = "#e2e8f0"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
